language: python
python:
  - '3.6'

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt


script:
- flake8
- mkdir for_test
- cd for_test
- py.test --pyargs Shared_Exp_Beh --cov-report term-missing --cov=Shared_Exp_Beh


after_success:
- coveralls