language: python
python:
  - '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt


script:
- mkdir for_test
- cd for_test
- pytest --pyargs Shared_Exp_Beh --cov-report term-missing --cov=Shared_Exp_Beh


after_success:
- coveralls